server.port=8080
shareit.server.url=http://localhost:9090
logging.level.ru.practicum.shareit=DEBUG
server.tomcat.max-http-response-header-size=8192
server.connection-timeout=5s
server.servlet.context-path=/