server.port=8080
shareit.server.url=http://localhost:9090
logging.level.ru.practicum.shareit=DEBUG
server.tomcat.max-http-response-header-size=8192
server.connection-timeout=5s
server.servlet.context-path=/
management.endpoints.web.exposure.include=health,info
management.endpoint.health.enabled=true
logging.level.org.springframework.web.client=DEBUG
logging.level.org.apache.http=WARN
server.http2.enabled=false
server.error.include-message=always