server.port=8080
shareit.server.url=http://shareit-server:9090
logging.level.ru.practicum.shareit=DEBUG
server.tomcat.max-http-response-header-size=8192
server.connection-timeout=5s
server.servlet.context-path=/
management.endpoints.web.exposure.include=health,info
management.endpoint.health.enabled=true